<?php
/**
 * TEST-ONLY mu-plugin (S22 pseudo-locale spec). Never shipped: this whole
 * `tests/` tree is excluded by `.distignore`, and this file is mapped into
 * wp-env's `mu-plugins` directory only by this worktree's `.wp-env.json` —
 * a normal install never sees it.
 *
 * Points WordPress at the pseudo-locale build artifacts under
 * `tests/e2e/pseudo-locale/build/` (generated by
 * `tests/e2e/support/pseudo-locale-build.js`) for the `senroflux` text
 * domain, whenever the CURRENT locale (`determine_locale()`, which for an
 * admin screen is the logged-in user's own `locale` user-meta) is the
 * pseudo-locale below — never site-wide, so no other spec's locale is
 * affected.
 *
 * @package SenroFlux
 */

defined( 'ABSPATH' ) || exit;

const SENROFLUX_PSEUDO_LOCALE    = 'en_XA';
const SENROFLUX_PSEUDO_BUILD_DIR = WP_CONTENT_DIR . '/plugins/senroflux/tests/e2e/pseudo-locale/build/';

// PHP translations (__(), _n(), esc_html__() etc. for the 'senroflux' domain).
add_filter(
	'load_textdomain_mofile',
	static function ( $mofile, $domain ) {
		if ( 'senroflux' === $domain && SENROFLUX_PSEUDO_LOCALE === determine_locale() ) {
			$override = SENROFLUX_PSEUDO_BUILD_DIR . 'senroflux-' . SENROFLUX_PSEUDO_LOCALE . '.mo';
			if ( file_exists( $override ) ) {
				return $override;
			}
		}
		return $mofile;
	},
	10,
	2
);

// JS translations (wp_set_script_translations( $handle, 'senroflux' )).
// One merged JSON file is served for every handle in this domain — see
// pseudo-locale-build.js's mergeJedJsonFiles() for why a single file is
// enough (the per-source-file split `wp i18n make-json` produces is an
// optimization we don't need for a test-only pseudo-locale).
add_filter(
	'load_script_translation_file',
	static function ( $file, $handle, $domain ) {
		if ( 'senroflux' === $domain && SENROFLUX_PSEUDO_LOCALE === determine_locale() ) {
			$override = SENROFLUX_PSEUDO_BUILD_DIR . 'senroflux-' . SENROFLUX_PSEUDO_LOCALE . '-merged.json';
			if ( file_exists( $override ) ) {
				return $override;
			}
		}
		return $file;
	},
	10,
	3
);
